name: cafe-bda
base: core24
version: '6.08.1'
summary: Une application Flutter pour gérer le café BDA
description: |
  Ceci est une application construite avec Flutter pour Linux.
grade: stable
confinement: strict

parts:
  cafe-bda:
    plugin: dump
    source: build/linux/x64/release/bundle/
    organize:
      '*': usr/share/cafe-bda/

apps:
  cafe-bda:
    command: usr/share/cafe-bda/cafe_bda
    desktop: cafe_bda.desktop
