// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa5NHbQpqK5d0jfkKENXBnT-dfDS6E3Ow',
    appId: '1:363270601733:web:d14fbc6cd6e690c572b06c',
    messagingSenderId: '363270601733',
    projectId: 'cafe-bda',
    authDomain: 'cafe-bda.firebaseapp.com',
    storageBucket: 'cafe-bda.firebasestorage.app',
    measurementId: 'G-0Q8M2Y8PN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVTWxi7DhOevMmoVMXk5CQ6piqaBq4kXs',
    appId: '1:363270601733:android:5a9b6fa1f68bf85372b06c',
    messagingSenderId: '363270601733',
    projectId: 'cafe-bda',
    storageBucket: 'cafe-bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaFVmLaM60wFNiCGCGsLrwi3pFkioLbVY',
    appId: '1:363270601733:ios:f05ad3d639db278172b06c',
    messagingSenderId: '363270601733',
    projectId: 'cafe-bda',
    storageBucket: 'cafe-bda.firebasestorage.app',
    iosBundleId: 'com.example.excelEditor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaFVmLaM60wFNiCGCGsLrwi3pFkioLbVY',
    appId: '1:363270601733:ios:f05ad3d639db278172b06c',
    messagingSenderId: '363270601733',
    projectId: 'cafe-bda',
    storageBucket: 'cafe-bda.firebasestorage.app',
    iosBundleId: 'com.example.excelEditor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa5NHbQpqK5d0jfkKENXBnT-dfDS6E3Ow',
    appId: '1:363270601733:web:00b40b57577222f272b06c',
    messagingSenderId: '363270601733',
    projectId: 'cafe-bda',
    authDomain: 'cafe-bda.firebaseapp.com',
    storageBucket: 'cafe-bda.firebasestorage.app',
    measurementId: 'G-8Q14951E70',
  );
}
