name: boutique_bda
description: "A new Flutter project."
publish_to: 'none'
version: 10.0.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  provider: ^6.1.5+1
  google_sign_in: 6.2.1
  intl: ^0.20.2
  firedart: ^0.9.8
  rxdart: ^0.28.0
  fl_chart: ^1.1.1
  qr_flutter: ^4.1.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/icon/logoBDA_4_complet.png"
  android: true
  ios: true
  remove_alpha_ios: true
  windows:
    image_path: "assets/icon/logoBDA_4_complet.png"
    generate: true
  linux:
    image_path: "assets/icon/logoBDA_4_complet.png"
    generate: true
  macos:
    image_path: "assets/icon/logoBDA_4_complet.png"
    generate: true

flutter:
  uses-material-design: true

  assets:
    - assets/icon/