// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMHf7EBW5epoiNba0-apBFtD9m5sqxvbM',
    appId: '1:278248091968:web:d0ea96211c1e8c733d8aa5',
    messagingSenderId: '278248091968',
    projectId: 'boutique-bda',
    authDomain: 'boutique-bda.firebaseapp.com',
    storageBucket: 'boutique-bda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBXexQJpwIrKuyRUJLK9J1yswhO48BB10',
    appId: '1:278248091968:android:1b9a4d909971508b3d8aa5',
    messagingSenderId: '278248091968',
    projectId: 'boutique-bda',
    storageBucket: 'boutique-bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK9F9zFa-X2L2nhaJwDuHbXcjXVQFgmGE',
    appId: '1:278248091968:ios:6e9a5ac31acc27eb3d8aa5',
    messagingSenderId: '278248091968',
    projectId: 'boutique-bda',
    storageBucket: 'boutique-bda.firebasestorage.app',
    iosBundleId: 'com.example.boutiqueBda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK9F9zFa-X2L2nhaJwDuHbXcjXVQFgmGE',
    appId: '1:278248091968:ios:6e9a5ac31acc27eb3d8aa5',
    messagingSenderId: '278248091968',
    projectId: 'boutique-bda',
    storageBucket: 'boutique-bda.firebasestorage.app',
    iosBundleId: 'com.example.boutiqueBda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMHf7EBW5epoiNba0-apBFtD9m5sqxvbM',
    appId: '1:278248091968:web:1e55c27e67886deb3d8aa5',
    messagingSenderId: '278248091968',
    projectId: 'boutique-bda',
    authDomain: 'boutique-bda.firebaseapp.com',
    storageBucket: 'boutique-bda.firebasestorage.app',
  );
}
